#!/bin/bash

guest=$1

# If the fresh install flag exist, unflag.
[[ ! -f $VA_PATH/utils/switch/registry/$guest ]] && ( mkdir $VA_PATH/utils/switch/registry & echo "" > $VA_PATH/utils/switch/registry/$guest )

# Switch module handles the handing over of I/O to the next guest/host (if no other guests are active.)
# We sleep and detach, due to the fact that there is a possibility that the host doesn't yet fully
# recover all the GPUs since vfio-startup is on always executed mode (see qemu script.)
( sleep 3 && $VA_DISPATCH switch/next ) &
